name = "smart-money-api"
main = "workers/api/index.ts"
compatibility_date = "2025-02-06"

# KV Namespace bindings
kv_namespaces = [
  { binding = "SMART_MONEY_CACHE", id = "4146d86894e74779a14b83e2124c4194", preview_id = "4146d86894e74779a14b83e2124c4194" }
]

# R2 bucket binding
[[r2_buckets]]
binding = 'SMART_MONEY_BUCKET'
bucket_name = 'smart-money-data'
preview_bucket_name = 'smart-money-data-dev'

[build]
command = "npm run build"

[triggers]
crons = ["0 * * * *"]  # Run every hour

[env.production]
name = "smart-money-api-production"
route = { pattern = "api.0xathena.ai/smart-money/*", zone_name = "0xathena.ai" }
workers_dev = false
deployment_protection = true

kv_namespaces = [
  { binding = "SMART_MONEY_CACHE", id = "4146d86894e74779a14b83e2124c4194" }
]

[[env.production.r2_buckets]]
binding = 'SMART_MONEY_BUCKET'
bucket_name = 'smart-money-data'

[env.development]
name = "smart-money-api-development"
workers_dev = true

[env.staging]
name = "smart-money-api-staging"
workers_dev = true
routes = [
  { pattern = "staging.api.0xathena.ai/smart-money/*", zone_name = "0xathena.ai" }
]
kv_namespaces = [
  { binding = "SMART_MONEY_CACHE", id = "4146d86894e74779a14b83e2124c4194" }
]
[[env.staging.r2_buckets]]
binding = 'SMART_MONEY_BUCKET'
bucket_name = 'smart-money-data-staging'

[env.dev]
name = "smart-money-api-dev"
routes = [
  { pattern = "dev.api.0xathena.ai/smart-money/*", zone_name = "0xathena.ai" }
]
workers_dev = true
kv_namespaces = [
  { binding = "SMART_MONEY_CACHE", id = "4146d86894e74779a14b83e2124c4194" }
]
[[env.dev.r2_buckets]]
binding = 'SMART_MONEY_BUCKET'
bucket_name = 'smart-money-data-dev'

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
