name: Deploy

on:
  push:
    branches:
      - main  # production
      - develop  # development
  pull_request:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm ci
        working-directory: cloudflare
        
      - name: Run Tests
        run: npm test
        working-directory: cloudflare

      - name: Deploy Development
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: development
          workingDirectory: 'cloudflare'
          
      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: production
          workingDirectory: 'cloudflare'
          preCommands: |
            echo "Running pre-deployment checks..."
            npm test
          postCommands: |
            echo "Running post-deployment verification..."
            curl -s https://api.0xathena.ai/smart-money/token-stats
